---
title: " Ensino Superior "
output: 
  flexdashboard::flex_dashboard:
    logo: figure/reconhecendosalvador.gif
    css: style.css
    social: menu
    orientation: columns
    vertical_layout: fill
    source_code: embed
---



```{r setup, include=FALSE}
library(flexdashboard)
#library(ggplot2)
library("DT")
library("readr")
library("dplyr")
library("ggplot2")
library("kableExtra")
library("tidyr")
library("formattable")
library("plotly")
library("ggplotlyExtra")
library("ggpubr")
library("tidyverse")
library("hrbrthemes")
library("waffle")
library(ggthemes)
library(extrafont)
library(gganimate)


library(echarts4r) # charts
library(tidyverse) # general use
library(lubridate) # dates and times
library(prophet) # forecasting


CENSO_SUP <- NULL
CENSO_SUP <- read_delim("data/educacao/CENSO_SUPERIOR/DM_ALUNO_2009_2018_CO_IES_by_ANO_TP_COR_RACA_TP_SEXO.csv",",",escape_double = FALSE,trim_ws = FALSE)
#CENSO_SUP$TP_SEXO <- ifelse(CENSO_SUP$TP_SEXO==1,"Feminino","Masculino")
CENSO_SUP$TP_SEXO <- ifelse(CENSO_SUP$TP_SEXO==1,"F","M")

# Transformacao da variavel numerica de acordo com o vocabulario 
CENSO_SUP$TP_COR_RACA <- ifelse(CENSO_SUP$TP_COR_RACA==0,"*NQD",
                                CENSO_SUP$TP_COR_RACA <- ifelse(CENSO_SUP$TP_COR_RACA==1,"Branca",CENSO_SUP$TP_COR_RACA <- ifelse(CENSO_SUP$TP_COR_RACA==2,"Preta",CENSO_SUP$TP_COR_RACA <- ifelse(CENSO_SUP$TP_COR_RACA==3,"Parda",CENSO_SUP$TP_COR_RACA <- ifelse(CENSO_SUP$TP_COR_RACA==4,"Amarela",CENSO_SUP$TP_COR_RACA <- ifelse(CENSO_SUP$TP_COR_RACA==5,"Indígena",CENSO_SUP$TP_COR_RACA <- ifelse(CENSO_SUP$TP_COR_RACA==9,"*NDI",NA)))))))

CONCLUINTES_SSA <- CENSO_SUP %>% filter(IN_CONCLUINTE==1)



HEAT_SSA_IES_SEXO_RACA <- CONCLUINTES_SSA %>% dplyr::group_by(ANO_CENSO_SUP,TP_SEXO,TP_COR_RACA) %>% summarise(quantidade = sum(value,na.rm = "TRUE")) 


#target = c("Amarela","Branca","Indígena","Parda","Preta")
target = c("Parda","Preta")
HEAT_SSA_IES_SEXO_RACA_S_NQD_NDI <- HEAT_SSA_IES_SEXO_RACA %>%  filter(TP_COR_RACA %in% target) %>%
  dplyr::group_by(ANO_CENSO_SUP,TP_SEXO,TP_COR_RACA) %>% 
  summarise(quantidadef = sum(quantidade,na.rm = "TRUE")) 


```

Column {data-width=300}
-------------------------------------

O número total de concluintes do ensino superior (biológico - definição IBGE) está disponível no gráfico 
de barras ao lado. Enquanto a total de 
concluintes (2009-2018) desagregados por sexo 
são apresentados nos cartões.

### Concluintes do Sexo Feminino

```{r}
Sexo_Feminino <- CONCLUINTES_SSA %>% filter(TP_SEXO %in% c("F")) %>% summarise(valor=sum(value))
valueBox(Sexo_Feminino, icon = "fa-pencil",href="#concluintes-f",
         color = "#fac113")
```

### Concluintes do Sexo Masculino

```{r}
Sexo_Masculino <- CONCLUINTES_SSA %>% filter(TP_SEXO %in% c("M")) %>% summarise(valor=sum(value))
valueBox(Sexo_Masculino, icon = "fa-pencil", href="#concluintes-m")
```

### Total de Concluintes

```{r}
Total <- CONCLUINTES_SSA %>% summarise(valor=sum(value))
valueBox(Total, 
         icon = "fa-child",
         color = ifelse(Total > 3000000, "warning", "#db4470"))
```

Column {data-width=800}
-------------------------------------   

### <font size="5"> **Nº total de concluintes em ensino superior** </font>

```{r, eval=TRUE, fig.height=4, fig.width=3}

CONCLUINTES_SSA %>% filter(TP_SEXO %in% c("F")) %>% group_by(ANO_CENSO_SUP) %>% summarise(value =sum(value)) %>% mutate(ANO_CENSO_SUP=as.character(ANO_CENSO_SUP)) %>%
  e_charts(x = ANO_CENSO_SUP) %>%   #,width = "100%", height = "200px") %>%
  e_bar(value,legend = FALSE, name = "Nº Concluintes") %>% 
  #e_labels(position = "right") %>% 
  e_labels(position = "top") %>% 
  e_tooltip() %>% 
  e_title("Sexo Feminino", "Total") %>% 
 # e_flip_coords() %>% 
  e_y_axis(splitLine = list(show = FALSE),formatter = e_axis_formatter("decimal", locale = "pt-br")) %>% 
  #e_x_axis(show = FALSE) %>%
  e_x_axis(show = TRUE) %>%
  e_color(
    c("#00c4cc", "#db4470"),
    "#ffffff"
  ) %>%  e_toolbox_feature(
    feature = "dataView",
    title = "Ver dados"
  ) %>% 
e_axis_labels(x ="",y= "") %>%
  e_tooltip(trigger="axis",
            axisPointer = list(
              type = "cross"),
            textStyle=list(fontFamily="arial",
                           fontSize=12)) %>%
  e_toolbox_feature(feature = "dataZoom") %>%  
  e_format_y_axis(suffix = "")  


```



